AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template Definition

Resources:
  UrlTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: url-shortener-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: short_id
          AttributeType: S
      KeySchema:
        - AttributeName: short_id
          KeyType: HASH

  UrlShortener:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app/main.lambda_handler
      Runtime: python3.12
      FunctionName: url-shortener
      MemorySize: 512
      Timeout: 900
      Environment:
        Variables:
          TABLE_NAME: !Ref UrlTable
      Policies:
        - AmazonSSMFullAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref UrlTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  UrlShortenerFunction:
    Description: URL Shortener Lambda Function ARN
    Value: !GetAtt UrlShortener.Arn
  UrlShortenerApi:
    Description: API Gateway endpoint URL for the URL Shortener
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  UrlTable:
    Description: DynamoDB Table Name
    Value: !Ref UrlTable
