AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template Definition

Resources:
  UrlTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
#    UpdateReplacePolicy: Retain
    Properties:
      TableName: url-shortener-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: short_id
          AttributeType: S
      KeySchema:
        - AttributeName: short_id
          KeyType: HASH

  UrlShortener:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app/main.lambda_handler
      Runtime: python3.12
      FunctionName: url-shortener
      MemorySize: 356
      Timeout: 60
      Environment:
        Variables:
          TABLE_NAME: !Ref UrlTable
          API_ENDPOINT: "https://s-hrt.com/"
          REDIS_CONFIG: redis-config
      Policies:
        - AmazonSSMFullAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref UrlTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

#  CounterUpdateQueue:
#    Type: AWS::SQS::Queue
#    Properties:
#      QueueName: url-shortener-counter-queue
#      VisibilityTimeout: 30
#      MessageRetentionPeriod: 3600
#
#  CounterUpdateFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      CodeUri: .
#      Handler: app/counter_update.lambda_handler
#      Runtime: python3.12
#      ReservedConcurrentExecutions: 1
#      Timeout: 30
#      Environment:
#        Variables:
#          TABLE_NAME: !Ref UrlTable
#      Policies:
#        - AmazonSQSFullAccess
#        - DynamoDBCrudPolicy:
#            TableName: !Ref UrlTable
#      Events:
#        SQSEvent:
#          Type: SQS
#          Properties:
#            Queue: !GetAtt CounterUpdateQueue.Arn
#            BatchSize: 10
#            MaximumBatchingWindowInSeconds: 30

Outputs:
  UrlShortenerFunction:
    Description: URL Shortener Lambda Function ARN
    Value: !GetAtt UrlShortener.Arn
  UrlShortenerApi:
    Description: API Gateway endpoint URL for the URL Shortener
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  UrlTable:
    Description: DynamoDB Table Name
    Value: !Ref UrlTable
